Add recommender system chapter
openmlsys/openmlsys-zh pull request #36
Opened 2022-03-06 12:04 UTC by future-xy

2022-03-06 14:59 UTC, eedalong commented on chapter_recommender_system/index.md
> +# 深度学习推荐系统
这个推荐系统这部分是单独的一个章么？还是某一章的一个小节

2022-03-06 19:29 UTC, future-xy commented on chapter_recommender_system/index.md
> +# 深度学习推荐系统
原来是按照一个小节写的，但是按照麦老师最新的安排，这个是独立的一个chapter

2022-03-07 00:58 UTC, eedalong commented on chapter_recommender_system/index.md
> +# 深度学习推荐系统
@future-xy  独立chapter么， okk～

2022-03-07 01:03 UTC, Laicheng0830 approved these changes

2022-03-07 01:31 UTC, eedalong approved these changes

2022-03-07 10:19 UTC, luomai requested changes

2022-03-08 03:23 UTC, Laicheng0830 commented on chapter_recommender_system/index.md
> +-   内存高效的嵌入项存储与计算。除了系统上的设计，研究人员也在探索其他算法优化手段来压缩嵌入表的内存需求。直接使用低精度浮点数可以有效降低内存开销，但是还是会对模型的精度产生一定的影响。因此在在线推荐服务这种精度敏感的场景中并不适用。除此之外，[@MLSYS2021_979d472a]利用低秩分解可以将一个大矩阵分解为两个小矩阵（向量）。这种方法可以在保留原矩阵大量信息的前提下显著减小内存开
@future-xy 参考文献的引用方式已经更新至STYLE_GUIDE.md

2022-03-10 08:34 UTC, merged